spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC%2B8
    username: root
    password: 123456
  security:
    jwt:
      key: reine-ishyanami
      expire: 7
    filter:
      order: -100
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update