spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: SpringBoot-Vue-Jwt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    jwt:
      key: reine-ishyanami
      expire: 7
    permit-url:
      - "/api/auth/**"
      - "/error"
      - "/swagger-ui**/**"
      - "/v3/api-docs/**"
      - "/doc.html"
      - "/webjars/**"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.163.com
    username: xxx
    password: xxx
image-host:
  baseUrl: http://localhost:8824/image/