spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC%2B8
    username: root
    password: 123456
  security:
    jwt:
      key: reine-ishyanami
      expire: 7
    filter:
      order: -100
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.163.com
    username: xxx
    password: xxx
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: 0
          max-idle: 5
          min-idle: 1
      timeout: 10000
logging:
  level:
    com.reine.backend:
      debug
