spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC%2B8
    username: root
    password: 123456
  security:
    jwt:
      key: reine-ishyanami
      expire: 7
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.163.com
    username: xxx
    password: xxx
logging:
  level:
    com.reine.backend:
      debug
